pub(crate) mod impls;
use std::rc::Rc;

pub trait Token {
    fn raw(&self) -> Rc<str>;
    fn source_position(&self) -> SourcePosition;
}

pub struct SourcePosition {
    pub row: u32,
    pub column: u32,
}

pub enum Keyword {
    //single character keywords
    BracketRoundOpen,
    BracketRoundClose,
    BracketCurlyOpen,
    BracketCurlyClose,
    BracketSquareOpen,
    BracketSquareClose,
    BracketDiamondOpen,
    BracketDiamondClose,
    QuoteSingle,
    QuoteDouble,
    MarkExclamation,
    MarkQuestion,
    Pipe,
    SlashForward,
    SlashBackward,
    Percent,
    And,
    Equals,
    Star,
    Plus,
    Minus,
    Underscore,
    Comma,
    Colon,
    ColonSemi,
    Period,
    Tilde,
    Hashtag,
    Caret,
    Degree,
    At,
    //double character keywords
    CommentLine,
    CommentStart,
    CommentEnd,
    EqualsDouble,
    EqualsLess,
    EqualsMore,
    EqualsNot,
    EqualsStar,
    EqualsSlash,
    EqualsPlus,
    EqualsMinus,
    EqualsPercent,
    EqualsAnd,
    EqualsPipe,
    EqualsTide,
    EqualsCaret,
    EqualsMarkQuestion,
    EqualsHashtag,
    EqualsDegree,
    EqualsAt,
    ShiftLeft,
    ShiftRight,
    AndDouble,
    PipeDouble,
    Arrow,
    ArrowFat,
    ColonDoubleDouble,
    //triple character keywords
    EqualsShiftLeft,
    EqualsShiftRight,
    EqualsAndDouble,
    EqualsPipeDouble,
    //word keywords
    Namespace,
    Import,
    Public,
    Local,
    Const,
    Mut,
    Struct,
    Var,
    Unsafe,
    Extern,
    Inline,
    Interface,
    Type,
    As,
    Fn,
    Break,
    Continue,
    If,
    Else,
    Switch,
    For,
    While,
    Return,
    Enum,
    Union,
    Static,
    Staged,
    Yield,
    In,
    Unsigned,
    With,
    Where,
    Super,
    Satisfies,
    Alloc,
    Implement,
    Ref,
    _Self,
    //lexer macro keywords
    __Line,
    __File,
}

pub struct KeywordToken {
    source_position: SourcePosition,
    keyword:Keyword,
}

